#!/usr/bin/env python3
"""Generate a content-based build identity without needless rebuilds."""
import hashlib
import os
import re
from pathlib import Path
import shlex
import subprocess
import sys


def fingerprint(root, config):
    digest = hashlib.sha256()
    def add(value):
        digest.update(len(value).to_bytes(8, "little"))
        digest.update(value)
    for name in ("qw3.c", "qw3.h", "qw3_metal.m", "qw3_metal.h",
                 "tools/runtime_fingerprint.py"):
        add(name.encode())
        add((root / name).read_bytes())
    for value in config:
        add(value.encode())
    return digest.digest()


if __name__ == "__main__":
    output = Path(sys.argv[1])
    config = sys.argv[2:]
    config.append(subprocess.check_output(
        shlex.split(config[0]) + ["--version"], text=True))
    config.append(subprocess.check_output(["uname", "-sm"], text=True))
    if sys.platform == "darwin":
        config.append(subprocess.check_output(
            ["xcrun", "--show-sdk-version", "--show-sdk-build-version"], text=True))
    for key in ("SDKROOT", "MACOSX_DEPLOYMENT_TARGET", "CPATH",
                "C_INCLUDE_PATH", "OBJC_INCLUDE_PATH"):
        config.append(key + "=" + os.environ.get(key, ""))
    data = fingerprint(Path(__file__).resolve().parent.parent, config)
    content = "/* Generated by tools/runtime_fingerprint.py. */\n"
    content += "#define QW3_RUNTIME_FINGERPRINT {" + ",".join(
        "0x%02x" % b for b in data) + "}\n"
    root = Path(__file__).resolve().parent.parent
    names = set(re.findall(r'"(QW3_[A-Z0-9_]+)"',
                          (root / "qw3.c").read_text() +
                          (root / "qw3_metal.m").read_text()))
    names -= {"QW3_METAL_KERNEL_SOURCE", "QW3_METAL_KERNEL_DIR",
              "QW3_METAL_FLASH_ATTN_SOURCE"}
    content += "#define QW3_RUNTIME_ENV_NAMES {" + ",".join(
        '"' + name + '"' for name in sorted(names)) + ",NULL}\n"
    if not output.exists() or output.read_text() != content:
        temp = output.with_suffix(".tmp")
        temp.write_text(content)
        temp.replace(output)
